### ISSUE TITLE
Добавить возможность копировать текст из условия, а также код при просмотре посылки

### ISSUE THREAD

**Issue by afentev** [victor-yacovlev/yajudge#15]
Иногда очень хочется, чтобы была такая возможность. Например, чтобы скопировать и сразу загуглить какую-нибудь функцию, упомянутую в условии задачи

**Comment by victor-yacovlev** [comment]
Такая возможность исключена намеренно, чтобы усложнить копирование условий задач во избежание читерства.

Про "загуглить" какую-то функцию в условии задачи, - пожелание принимается, в условия добавлю прямые ссылки на соотвествующие маны.
