### ISSUE TITLE
Рандомные посылки получают вердикт "Ошибка тестирования"

### ISSUE THREAD

**Issue by afentev** [victor-yacovlev/yajudge#16]
Лог тестирующей системы: No files in solution, хотя прямо над этой надписью показан код отправленного файла. Эта ошибка появляется без видимой закономерности. Примеры таких посылок: ID = 2935, 2943

**Comment by victor-yacovlev** [comment]
Пытаемся поймать

**Comment by victor-yacovlev** [comment]
Удалось поймать и истребить.
